name: Tests Build

on:
  push:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]

jobs:

  build:

    name: Run tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: osp
          POSTGRES_PASSWORD: osp
          POSTGRES_DB: osp
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: ‘2’

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    
    - name: Installing dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage==5.4
    
    - name: Creating Zulip API key
      run: echo -e "${{ secrets.ZULIP_API_KEY }}" >> download

    - name: Migrating Test Database
      run: python manage.py migrate

    - name: Run tests
      run: coverage run manage.py test

    - name: Generate coverage report
      run: coverage xml

    - name: Upload coverage to Codecov on pull request
      uses: codecov/codecov-action@v1
      if: github.event_name == 'pull_request_target'
      with:
        name: codecov-umbrella
        override_pr: ${{ github.event.number }}
        override_sha: ${{ github.event.pull_request.head.sha }}
        files: ./coverage.xml
        fail_ci_if_error: true

    - name: Upload coverage to Codecov on push
      uses: codecov/codecov-action@v1
      if: github.event_name == 'push'
      with:
        file: ./coverage.xml
        name: codecov-umbrella
        fail_ci_if_error: true
